all: xdp.exe

xdp.exe: XDP.PAS XDPGEN.PAS XDPGLOB.PAS XDPOPT.PAS XDPPARS.PAS XDPSCAN.PAS XDPUTILS.PAS
        fpc -O4 XDP.PAS

clean:
        del *.ppu
        del *.o
        del *.bak
        del xdp.exe


