all: xdpc.exe

xdpc.exe: XDPC.PAS XDGEN.PAS XDTYPES.PAS XDGLOB.PAS XDOPT.PAS XDPARS.PAS XDSCAN.PAS XDUTILS.PAS XDLINK.PAS
        fpc -O4 -MDELPHI XDPC.PAS

install: xdpc.exe
        copy xdpc.exe ..\xdpc.exe

clean:
        del *.ppu
        del *.o
        del *.bak
        del xdpc.exe


